### ISSUE TITLE
220 dev-tools bom: terraform validate fails with the following error:

### ISSUE THREAD

**Issue by RamyaRaghuveera** [cloud-native-toolkit/terraform-gitops-sonarqube#23]
Error: Invalid value for module argument
│ 
│   on main.tf line 66, in module "gitops-sonarqube":
│   66:   postgresql = var.gitops-sonarqube_postgresql
│ 
│ The given value is not suitable for child module variable "postgresql" defined at .terraform/modules/gitops-sonarqube/variables.tf:109,1-22: object required.

**Comment by seansund** [comment]
This is an issue with the metadata generation, not the module.yaml file or anything else the module is doing
